= Lutaml

== Functionality

Entry point for lutaml extensions.

=== Installation

With bundler:

[source,ruby]
----
# Gemfile
gem "lutaml"
----

Then in console:

[source,console]
----
$ bundle
----

With RubyGems:

[source,console]
----
$ gem install lutaml
----

=== Usage

== From ruby

In order to parse files supported by lutaml extensions, use Lutaml::Parser.parse method.

[source,ruby]
----
# example.exp is an EXPRESS repository file
Lutaml::Parser.parse([File.new("example.exp")]) # will produce Lutaml::LutamlPath::DocumentWrapper object with serialized express repository
# example.yaml is an EXPRESS cache file
Lutaml::Parser.parse([File.new("example.yaml")], ::Lutaml::Parser::EXPRESS_CACHE_PARSE_TYPE)
----

== With cli tool

There is a cli tool available for parsing lutaml/exp files(also yaml datastruct files are supported).

[source,bash]
----
# Will generate `test.dot` file in the current directory
$: lutaml -o . test.lutaml

# Will generate `test.png` file in the `assets` directory
$: lutaml -o assets -t png test.lutaml
----

For additional info refer to `lutaml --help output`


== Development

After checking out the repo, run `bin/setup` to install dependencies. Then, run `rake spec` to run the tests. You can also run `bin/console` for an interactive prompt that will allow you to experiment.

To install this gem onto your local machine, run `bundle exec rake install`. To release a new version, update the version number in `version.rb`, and then run `bundle exec rake release`, which will create a git tag for the version, push git commits and tags, and push the `.gem` file to [rubygems.org](https://rubygems.org).

## Contributing

Bug reports and pull requests are welcome on GitHub at https://github.com/[USERNAME]/lutaml. This project is intended to be a safe, welcoming space for collaboration, and contributors are expected to adhere to the [code of conduct](https://github.com/[USERNAME]/lutaml/blob/master/CODE_OF_CONDUCT.md).


== Code of Conduct

Everyone interacting in the Lutaml::Uml project's codebases, issue trackers, chat rooms and mailing lists is expected to follow the [code of conduct](https://github.com/[USERNAME]/lutaml/blob/master/CODE_OF_CONDUCT.md).