# frozen_string_literal: true

source "https://rubygems.org"

gem "jekyll"
gem "just-the-docs"
gem "jekyll-asciidoc"
gem "jekyll-seo-tag"
gem "jekyll-sitemap"

group :jekyll_plugins do
  gem "asciidoctor"
end