name: rake

on:
  push:
    branches: [ master, main ]
    tags: [ v* ]
  pull_request:
  workflow_dispatch:

jobs:
  rake:
    uses: metanorma/metanorma-build-scripts/.github/workflows/graphviz-rake.yml@main
    secrets:
      pat_token: ${{ secrets.METANORMA_CI_PAT_TOKEN }}
